"""add tool_arguments to messages

Revision ID: 32d00c7f64a2
Revises: d25ae8ea7e38
Create Date: 2026-04-28 10:40:54.999723

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32d00c7f64a2"
down_revision: Union[str, Sequence[str], None] = "d25ae8ea7e38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("tool_arguments", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "tool_arguments")
    # ### end Alembic commands ###
