"""message content nullable

Revision ID: d25ae8ea7e38
Revises: 231ea708e919
Create Date: 2026-04-28 10:09:05.686722

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d25ae8ea7e38"
down_revision: Union[str, Sequence[str], None] = "231ea708e919"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "content", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "content", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
